import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function validateModelsData(data: string) {
  let catalog: unknown
  try {
    catalog = JSON.parse(data)
  } catch {
    throw new Error("Model catalog must be valid JSON")
  }

  if (!isRecord(catalog)) {
    throw new Error("Model catalog must contain at least one provider and one model")
  }
  const providers = Object.values(catalog)
  let modelCount = 0
  for (const provider of providers) {
    if (!isRecord(provider) || !isRecord(provider.models)) continue
    modelCount += Object.keys(provider.models).length
  }
  if (providers.length === 0 || modelCount === 0) {
    throw new Error("Model catalog must contain at least one provider and one model")
  }
}

validateModelsData(modelsData)
await Bun.write(
  path.join(dir, "../core/src/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "../core/src/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
